### ISSUE TITLE
Error on Boot

### ISSUE THREAD

**Issue by imjack** [ProjectInfinity/PocketVote-Nukkit#1]
00:25:21 [CRITICAL Exception while async task 0 invoking onCompletion ]
java.lang.NullPointerException
    at io.pocketvote.task.VoteCheckTask.lambda$onCompletion$1(VoteCheckTask.java:85)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:18
01)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:1
74)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at io.pocketvote.task.VoteCheckTask.onCompletion(VoteCheckTask.java:85)
    at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
    at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:300
)
    at cn.nukkit.Server.tick(Server.java:1018)
    at cn.nukkit.Server.tickProcessor(Server.java:808)
    at cn.nukkit.Server.start(Server.java:787)
    at cn.nukkit.Server.<init>(Server.java:472)
    at cn.nukkit.Nukkit.main(Nukkit.java:68)

Sorry about the formatting. This happens once the sever starts.

**Comment by ProjectInfinity** [comment]
Does this happen all the time or just sometimes?

**Comment by imjack** [comment]
It's been happening every time I've had the time to look

**Comment by imjack** [comment]
What was the issue then

**Comment by ProjectInfinity** [comment]
IPs don't seem to be forwarded anymore. Could be a change from a voting
site, however I'm unsure because PocketVote API is now on v2 which is
completely rewritten and the nukkit plugin stil uses api v1
