### ISSUE TITLE
where do i put my vrc?

### ISSUE THREAD

**Issue by XDqrkneZ** [ProjectInfinity/PocketVote-Nukkit#7]
i have my server on https://minecraftpocket-servers.com and i got my vrc but where  do i put it?
and what do i put in secret and identity?

**Comment by ProjectInfinity** [comment]
Vrc is not released yet. But you need to create a vrc folder in your
PocketVote plugins folder.

But I think the website you linked has native support for pocketvote.

**Comment by XDqrkneZ** [comment]
i created vrc inside PocketVote folder and put the vrc i downloaded from the website. but still not work

**Comment by ProjectInfinity** [comment]
I've set up Travis and tagged a release. You can download the JAR file here: https://github.com/ProjectInfinity/PocketVote-Nukkit/releases/tag/2.0.0-alpha.1

**Comment by XDqrkneZ** [comment]
17:15:12 [INFO] Loading PocketVote v2.0.0-bDEV
17:15:12 [CRITICAL] Could not execute taskHandler 91: io/pocketvote/PocketVote has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
17:15:12 [ALERT] java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: io/pocketvote/PocketVote has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:298)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:276)
        at cn.nukkit.Server.tick(Server.java:1082)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:508)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.UnsupportedClassVersionError: io/pocketvote/PocketVote has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:141)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:40)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:47)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:268)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.reload(Server.java:733)
        at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:247)
        at cn.nukkit.Server.dispatchCommand(Server.java:688)
        at cn.nukkit.command.CommandReader.lambda$run$0(CommandReader.java:75)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:295)
        ... 6 more

**Comment by ProjectInfinity** [comment]
You need to update to Java 1.9.

**Comment by XDqrkneZ** [comment]
but i dont think nukkit support 1.9 and i cant download to 1.9 java

**Comment by ProjectInfinity** [comment]
I'm using nukkit on Java 1.9.

**Comment by XDqrkneZ** [comment]
can you send java 1.9 download? i tried searching and it gives me java 10

**Comment by XDqrkneZ** [comment]
is the latest releases supposed to support vrc? if so it doesnt create folder vrc

**Comment by ProjectInfinity** [comment]
No. You must create the folder yourself. VRC is a power user feature that is only intended for people who know what they are doing because all voting sites should support standard PocketVote and not the legacy VRC format.

**Comment by XDqrkneZ** [comment]
oh. so then what do i put for this line? 
identity: ''
secret: ''

**Comment by ProjectInfinity** [comment]
Enter the information you get when you click your server on https://pocketvote.io
